NAME = libft.a

GNL_DIR = ./Get_Next_Line

SOURCES_MAND = ft_isalpha.c \
			ft_isdigit.c \
			ft_isalnum.c \
			ft_isascii.c \
			ft_isprint.c \
			ft_strlen.c \
			ft_memset.c \
			ft_bzero.c \
			ft_memcpy.c \
			ft_memmove.c \
			ft_strlcpy.c \
			ft_strlcat.c \
			ft_toupper.c \
			ft_tolower.c \
			ft_strchr.c \
			ft_strrchr.c \
			ft_strncmp.c \
			ft_memchr.c \
			ft_memcmp.c \
			ft_strnstr.c \
			ft_atoi.c \
			ft_calloc.c \
			ft_strdup.c \
			ft_substr.c \
			ft_strjoin.c \
			ft_strtrim.c \
			ft_split.c \
			ft_itoa.c \
			ft_strmapi.c \
			ft_striteri.c \
			ft_putchar_fd.c \
			ft_putstr_fd.c \
			ft_putendl_fd.c \
			ft_putnbr_fd.c \
			ft_iswhitespace.c \
			ft_atol.c \

SOURCES_BONUS = ft_lstnew.c \
			ft_lstadd_front.c \
			ft_lstsize.c \
			ft_lstlast.c \
			ft_lstadd_back.c \
			ft_lstdelone.c \
			ft_lstclear.c \
			ft_lstiter.c \
			ft_lstmap.c \

GNL_SOURCES = $(GNL_DIR)/get_next_line.c \
			$(GNL_DIR)/get_next_line_utils.c \

OBJS_MAND = $(SOURCES_MAND:.c=.o)
OBJS_BONUS = $(SOURCES_BONUS:.c=.o)
OBJS_GNL = $(GNL_SOURCES:.c=.o)

CC = cc
CFLAGS = -Wall -Wextra -Werror

AR = ar

all: $(NAME)

$(NAME): $(OBJS_MAND)
	$(AR) rcs $(NAME) $(OBJS_MAND)

bonus: $(OBJS_MAND) $(OBJS_BONUS)
	$(AR) rcs $(NAME) $(OBJS_MAND) $(OBJS_BONUS)

gnl: $(OBJS_GNL)
	$(AR) rcs $(NAME) $(OBJS_GNL)

clean:
	@rm -f $(OBJS_MAND) $(OBJS_BONUS) $(OBJS_GNL)

fclean: clean
	@rm -f $(NAME)

re: fclean all

.PHONY: all bonus clean fclean re gnl